In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37],[69, 96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69,96, 70], [73, 67, 43], [91, 88, 64]], dtype='float32')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119],[56, 70], [81, 101]],dtype='float32')

inputs, targets

(array([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]], dtype=float32), array([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.]], dtype=float32))

In [3]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.]]))

In [4]:
# Import tensor dataset and data loader
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F


In [5]:
# Define dataset
dataset = TensorDataset(inputs,targets)
dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [6]:
# Define data loader
dataloader = DataLoader(dataset,batch_size=15, shuffle=True)

In [7]:
# Define a model using nn.Linear
# Initializing weights and biases - nn.Linear

model = nn.Linear(in_features=3, out_features=2, bias=True)

In [8]:
# Manipulating the weights and biases - optimizer - optim.SGD
optimizer = torch.optim.SGD(model.parameters(), 0.0001)

In [9]:
# Loss function - torch.nn.functional.mse_loss
loss_fn = F.mse_loss

In [10]:
def fit(num_epochs:int, model, loss_fn, optimizer):
  for epoch in range(num_epochs):
    batch = 0
    for xb,yb in dataloader:
      batch += 1
      pred = model(xb)
      loss = loss_fn(pred, yb)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print('epoch {} batch {} batch size {} loss {}'.format(epoch,batch,len(xb),loss.item()))

fit(1000, model, loss_fn, optimizer)

epoch 0 batch 1 batch size 12 loss 9037.8818359375
epoch 1 batch 1 batch size 12 loss 5495.78271484375
epoch 2 batch 1 batch size 12 loss 3438.361328125
epoch 3 batch 1 batch size 12 loss 2233.3896484375
epoch 4 batch 1 batch size 12 loss 1518.9010009765625
epoch 5 batch 1 batch size 12 loss 1087.5543212890625
epoch 6 batch 1 batch size 12 loss 820.482421875
epoch 7 batch 1 batch size 12 loss 649.4537963867188
epoch 8 batch 1 batch size 12 loss 535.2244873046875
epoch 9 batch 1 batch size 12 loss 455.154052734375
epoch 10 batch 1 batch size 12 loss 396.118896484375
epoch 11 batch 1 batch size 12 loss 350.4570617675781
epoch 12 batch 1 batch size 12 loss 313.64752197265625
epoch 13 batch 1 batch size 12 loss 282.9787902832031
epoch 14 batch 1 batch size 12 loss 256.78887939453125
epoch 15 batch 1 batch size 12 loss 234.02687072753906
epoch 16 batch 1 batch size 12 loss 214.002197265625
epoch 17 batch 1 batch size 12 loss 196.23936462402344
epoch 18 batch 1 batch size 12 loss 180.3946075

In [11]:
new_data = torch.Tensor([[87, 134, 58], [102, 43, 37], [69, 96,70]])
new_targets = torch.Tensor([[119, 133], [22, 37], [103, 119]])
pred_new_data = model(new_data)
print("Predict (after training): ",new_targets,"\n", pred_new_data)

Predict (after training):  tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]]) 
 tensor([[118.6104, 132.9562],
        [ 20.8593,  37.0219],
        [101.6830, 119.1614]], grad_fn=<AddmmBackward0>)
