In [4]:
import numpy as np
import torch
import torch.nn as nn

In [5]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58],
                   [102, 43, 37],[69, 96, 70], [73, 67, 43],
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69,96, 70], [73, 67, 43], [91, 88, 64]], dtype='float32')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119],[56, 70], [81, 101]],dtype='float32')

inputs, targets

(array([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.]], dtype=float32), array([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.]], dtype=float32))

In [6]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

inputs, targets

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [ 91.,  88.,  64.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.]]))

In [7]:
# Import tensor dataset and data loader
from torch.utils.data import TensorDataset, DataLoader
import torch.nn.functional as F


In [8]:
# Define dataset
dataset = TensorDataset(inputs,targets)
dataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [9]:
# Define data loader
dataloader = DataLoader(dataset,batch_size=15, shuffle=True)

In [10]:
# Define a model using nn.Linear
# Initializing weights and biases - nn.Linear

model = nn.Linear(in_features=3, out_features=2, bias=True)

In [11]:
# Manipulating the weights and biases - optimizer - optim.SGD
optimizer = torch.optim.SGD(model.parameters(), 0.0001)

In [12]:
# Loss function - torch.nn.functional.mse_loss
loss_fn = F.mse_loss

In [13]:
def fit(num_epochs:int, model, loss_fn, optimizer):
  for epoch in range(num_epochs):
    batch = 0
    for xb,yb in dataloader:
      batch += 1
      pred = model(xb)
      loss = loss_fn(pred, yb)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print('epoch {} batch {} batch size {} loss {}'.format(epoch,batch,len(xb),loss.item()))

fit(1000, model, loss_fn, optimizer)

epoch 0 batch 1 batch size 12 loss 7933.61962890625
epoch 1 batch 1 batch size 12 loss 4657.21044921875
epoch 2 batch 1 batch size 12 loss 2771.432861328125
epoch 3 batch 1 batch size 12 loss 1682.2930908203125
epoch 4 batch 1 batch size 12 loss 1049.90478515625
epoch 5 batch 1 batch size 12 loss 679.7432250976562
epoch 6 batch 1 batch size 12 loss 460.4416809082031
epoch 7 batch 1 batch size 12 loss 328.20892333984375
epoch 8 batch 1 batch size 12 loss 246.47557067871094
epoch 9 batch 1 batch size 12 loss 194.2521514892578
epoch 10 batch 1 batch size 12 loss 159.46791076660156
epoch 11 batch 1 batch size 12 loss 135.1603240966797
epoch 12 batch 1 batch size 12 loss 117.29492950439453
epoch 13 batch 1 batch size 12 loss 103.5173568725586
epoch 14 batch 1 batch size 12 loss 92.43896484375
epoch 15 batch 1 batch size 12 loss 83.2283706665039
epoch 16 batch 1 batch size 12 loss 75.37604522705078
epoch 17 batch 1 batch size 12 loss 68.56084442138672
epoch 18 batch 1 batch size 12 loss 62.5

In [ ]:
new_data = torch.Tensor([[87, 134, 58], [102, 43, 37], [69, 96,70]])
new_targets = torch.Tensor([[119, 133], [22, 37], [103, 119]])
pred_new_data = model(new_data)
print("Predict (after training): ",new_targets,"\n", pred_new_data)

Predict (after training):  tensor([[119., 133.],
        [ 22.,  37.],
        [103., 119.]]) 
 tensor([[118.6104, 132.9562],
        [ 20.8593,  37.0219],
        [101.6830, 119.1614]], grad_fn=<AddmmBackward0>)
